env:
  device: mps
model:
  type: ollama
  url: http://localhost:11434/api/chat
  name: llama3
dataset:
  type: hf
  name: Sp1786/multiclass-sentiment-analysis-dataset
  batch_size: 1
  samples: 10
classifier:
  - id: FinancialBERT
    type: transformers
    name: ahmedrachid/FinancialBERT-Sentiment-Analysis
    output: class
    labels: 
      - positive
      - neutral
      - negative
  - id: ollama3
    type: ollama
    url: http://localhost:11434/api/chat
    name: llama3
    output: class
    labels: 
      - positive
      - neutral
      - negative
  - id: ollama3.2
    type: ollama
    url: http://localhost:11434/api/chat
    name: llama3.2
    output: class
    labels: 
      - positive
      - neutral
      - negative
evaluation:
  method: CC